In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv("C:/Users/Sai Prashanth/Desktop/PRACTICAL ENGINEERS/Heart_v1.csv")
df.head()
df['SBP'] = df['SBP'].replace(np.nan,0)
df['DBP'] = df['DBP'].replace(np.nan,0)
df

,NAME,AGE,GEN,R-R,SBP,DBP,TDL,HDL,LDL,Triglycerides,A/S,Arrhythmia,Coronary Artery Disease,Diabetes Mellitus,Hypertension,Myocardial INF,Obese,BMI
0,A100,69,0,0.433,0.0,0.0,187.2,65,100,111,0,1,0,1,0,0,1,32
1,A105,84,1,0.364,0.0,0.0,170.0,90,60,100,1,1,0,1,0,0,1,29
2,A119,51,1,0.268,0.0,0.0,205.0,110,80,75,1,1,0,0,1,0,0,23
3,A207,89,1,0.312,0.0,0.0,173.0,85,70,90,0,1,0,0,0,0,0,22
4,A208,23,1,0.385,0.0,0.0,220.0,100,90,150,0,1,0,0,1,0,1,28
5,A213,61,0,0.512,0.0,0.0,166.0,70,80,80,1,1,0,0,1,0,0,25
6,A221,83,0,0.452,0.0,0.0,190.0,130,40,100,1,1,0,1,0,0,0,24
7,A116,68,0,0.440,0.0,0.0,175.0,80,80,75,1,1,0,1,0,0,1,31
8,A203,43,0,0.530,0.0,0.0,185.0,125,50,50,1,1,0,0,1,0,0,24
9,A106,24,1,0.366,0.0,0.0,201.2,105,70,131,1,1,0,0,1,1,1,27
10,PT001,81,1,0.980,160.0,80.0,300.0,40,180,400,0,0,1,1,0,1,1,28
11,PT004,69,0,1.060,150.0,70.0,306.0,48,200,290,1,0,1,1,0,1,0,25
12,PT006,62,1,0.800,110.0,90.0,282.0,55,170,285,0,0,1,0,0,1,0,21
13,PT010,46,0,1.340,180.0,80.0,329.0,30,220,395,1,0,1,0,1,1,1,30
14,PT025,76,0,1.042,160.0,70.0,259.0,60,140,295,0,0,1,0,1,0,0,24
15,PT037,50,0,1.334,170.0,70.0,330.0,35,210,425,0,0,1,0,1,1,1,32
16,PT049,42,1,0.755,110.0,90.0,265.0,45,160,300,1,0,1,0,1,1,0,22
17,PT072,40,0,1.220,120.0,60.0,320.0,25,230,325,0,0,1,0,1,1,0,24
18,PT089,80,1,0.960,140.0,90.0,254.0,40,160,270,0,0,1,1,0,1,1,28
19,PT092,44,1,0.712,120.0,85.0,266.0,46,170,250,1,0,1,0,1,1,0,20
20,QT112,52,0,1.316,170.0,80.0,320.0,30,220,350,1,0,1,0,1,1,1,30
21,QT603,61,0,1.080,180.0,80.0,279.0,44,180,275,0,0,1,0,0,1,0,25
22,QT231,72,1,0.880,130.0,80.0,294.0,45,190,295,1,0,1,1,0,1,1,27
23,QT607,70,1,0.820,135.0,90.0,250.0,55,150,225,0,0,1,0,0,1,0,21
24,B1,24,0,0.620,125.0,75.0,195.0,90,90,75,0,0,0,0,0,0,0,24
25,G1,36,1,0.600,125.0,80.0,185.0,75,100,50,0,0,0,0,0,0,0,20
26,B2,46,0,0.720,130.0,70.0,195.0,105,70,100,0,0,0,0,0,0,0,25
27,G2,52,1,0.580,130.0,80.0,199.0,100,80,95,0,0,0,0,0,0,0,21
28,B3,63,0,0.680,140.0,75.0,197.0,65,120,60,0,0,0,0,0,0,0,23
29,G3,76,1,0.660,110.0,85.0,193.0,70,110,65,0,0,0,0,0,0,0,22

In [3]:
X1 = df.iloc[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23],[1,2,3,6,7,8,9,10,12,13,16,17]]
X2 = df.iloc[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23],[1,2,3,7,8,12,13,16]]
X3 = df.iloc[[10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29],[1,3,4,5,7,8,10,12,13,16,17]]

y1 = df.iloc[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23],[11]]
y2 = df.iloc[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23],[14]]
y3 = df.iloc[[10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29],[15]]


print(X1,X2)
print(y1,y2,y3)

    AGE  GEN    R-R    TDL  HDL  LDL  Triglycerides  A/S  \
1    84    1  0.364  170.0   90   60            100    1
2    51    1  0.268  205.0  110   80             75    1
3    89    1  0.312  173.0   85   70             90    0
4    23    1  0.385  220.0  100   90            150    0
5    61    0  0.512  166.0   70   80             80    1
6    83    0  0.452  190.0  130   40            100    1
7    68    0  0.440  175.0   80   80             75    1
8    43    0  0.530  185.0  125   50             50    1
9    24    1  0.366  201.2  105   70            131    1
10   81    1  0.980  300.0   40  180            400    0
11   69    0  1.060  306.0   48  200            290    1
12   62    1  0.800  282.0   55  170            285    0
13   46    0  1.340  329.0   30  220            395    1
14   76    0  1.042  259.0   60  140            295    0
15   50    0  1.334  330.0   35  210            425    0
16   42    1  0.755  265.0   45  160            300    1
17   40    0  1.220  320.0   25  230            325    0
18   80    1  0.960  254.0   40  160            270    0
19   44    1  0.712  266.0   46  170            250    1
20   52    0  1.316  320.0   30  220            350    1
21   61    0  1.080  279.0   44  180            275    0
22   72    1  0.880  294.0   45  190            295    1
23   70    1  0.820  250.0   55  150            225    0

    Coronary Artery Disease  Diabetes Mellitus  Obese  BMI
1                         0                  1      1   29
2                         0                  0      0   23
3                         0                  0      0   22
4                         0                  0      1   28
5                         0                  0      0   25
6                         0                  1      0   24
7                         0                  1      1   31
8                         0                  0      0   24
9                         0                  0      1   27
10                        1                  1      1   28
11                        1                  1      0   25
12                        1                  0      0   21
13                        1                  0      1   30
14                        1                  0      0   24
15                        1                  0      1   32
16                        1                  0      0   22
17                        1                  0      0   24
18                        1                  1      1   28
19                        1                  0      0   20
20                        1                  0      1   30
21                        1                  0      0   25
22                        1                  1      1   27
23                        1                  0      0   21       AGE  GEN    R-R  HDL  LDL  Coronary Artery Disease  Diabetes Mellitus  \
1    84    1  0.364   90   60                        0                  1
2    51    1  0.268  110   80                        0                  0
3    89    1  0.312   85   70                        0                  0
4    23    1  0.385  100   90                        0                  0
5    61    0  0.512   70   80                        0                  0
6    83    0  0.452  130   40                        0                  1
7    68    0  0.440   80   80                        0                  1
8    43    0  0.530  125   50                        0                  0
9    24    1  0.366  105   70                        0                  0
10   81    1  0.980   40  180                        1                  1
11   69    0  1.060   48  200                        1                  1
12   62    1  0.800   55  170                        1                  0
13   46    0  1.340   30  220                        1                  0
14   76    0  1.042   60  140                        1                  0
15   50    0  1.334   35  210                        1                  0
16   42    1  0.755   45  160                        1                  0
17   40    0  1.220   25  230                        1                  0
18   80    1  0.960   40  160                        1                  1
19   44    1  0.712   46  170                        1                  0
20   52    0  1.316   30  220                        1                  0
21   61    0  1.080   44  180                        1                  0
22   72    1  0.880   45  190                        1                  1
23   70    1  0.820   55  150                        1                  0

    Obese
1       1
2       0
3       0
4       1
5       0
6       0
7       1
8       0
9       1
10      1
11      0
12      0
13      1
14      0
15      1
16      0
17      0
18      1
19      0
20      1
21      0
22      1
23      0
    Arrhythmia
1            1
2            1
3            1
4            1
5            1
6            1
7            1
8            1
9            1
10           0
11           0
12           0
13           0
14           0
15           0
16           0
17           0
18           0
19           0
20           0
21           0
22           0
23           0     Hypertension
1              0
2              1
3              0
4              1
5              1
6              0
7              0
8              1
9              1
10             0
11             0
12             0
13             1
14             1
15             1
16             1
17             1
18             0
19             1
20             1
21             0
22             0
23             0     Myocardial  INF
10                1
11                1
12                1
13                1
14                0
15                1
16                1
17                1
18                1
19                1
20                1
21                1
22                1
23                1
24                0
25                0
26                0
27                0
28                0
29                0

In [4]:
from sklearn.model_selection import train_test_split
X1train,X1test,Y1train,Y1test = train_test_split(X1,y1,test_size = 0.3,random_state = 42)
X2train,X2test,Y2train,Y2test = train_test_split(X1,y2,test_size = 0.3,random_state = 30)
X3train,X3test,Y3train,Y3test = train_test_split(X3,y3,test_size = 0.3,random_state = 20)

print(X1test)

    AGE  GEN    R-R    TDL  HDL  LDL  Triglycerides  A/S  \
16   42    1  0.755  265.0   45  160            300    1
10   81    1  0.980  300.0   40  180            400    0
1    84    1  0.364  170.0   90   60            100    1
9    24    1  0.366  201.2  105   70            131    1
18   80    1  0.960  254.0   40  160            270    0
13   46    0  1.340  329.0   30  220            395    1
2    51    1  0.268  205.0  110   80             75    1

    Coronary Artery Disease  Diabetes Mellitus  Obese  BMI
16                        1                  0      0   22
10                        1                  1      1   28
1                         0                  1      1   29
9                         0                  0      1   27
18                        1                  1      1   28
13                        1                  0      1   30
2                         0                  0      0   23

In [55]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
X1train = sc_x.fit_transform(X1train)
X1test = sc_x.fit_transform(X1test)

X2train = sc_x.fit_transform(X2train)
X2test = sc_x.fit_transform(X2test)

X3train = sc_x.fit_transform(X3train)
X3test = sc_x.fit_transform(X3test)

#print(X1train)
print(X1test)

#print(X2train)
#print(X2test)

#print(X3train)
#print(X3test)

[[ 0.0200361  -1.          0.29337391  0.5688573  -0.09608896  0.60302269
  -0.0409807   0.77459667  0.37796447  1.         -1.29099445 -0.58536941]
 [ 0.98176878  1.          0.01644279  0.44474298 -0.53535278  0.20100756
   1.16111984 -1.29099445  0.37796447  1.          0.77459667  0.41812101]
 [ 0.26046927  1.         -0.32972112  0.32062866 -0.26081289  0.40201513
   0.01366023  0.77459667  0.37796447  1.          0.77459667  0.0836242 ]
 [ 0.58104683 -1.          0.23106441 -0.40337154  0.56280677 -0.60302269
   0.01366023 -1.29099445  0.37796447 -1.         -1.29099445 -0.91986621]
 [-1.34241853 -1.          1.17955352  0.85845738 -1.08443256  1.00503782
   0.61471051  0.77459667  0.37796447 -1.          0.77459667  1.08711461]
 [ 1.22220195  1.         -2.1159269  -2.24440063  2.2100461  -2.21108319
  -2.11733619  0.77459667 -2.64575131  1.          0.77459667  0.75261781]
 [-1.82328487 -1.          1.26263286  1.04462886 -1.08443256  1.00503782
   1.10647891  0.77459667  0.37796447 -1.          0.77459667  1.08711461]
 [ 0.10018049  1.         -0.53741947 -0.58954302  0.28826688 -0.40201513
  -0.75131284 -1.29099445  0.37796447 -1.         -1.29099445 -1.92335662]]

In [5]:
from sklearn.svm import SVR
from sklearn.metrics import r2_score

regr = SVR(kernel = 'linear')
regr.fit(X1train,Y1train)

train_Y_ = regr.predict(X1train)
test_Y_ = regr.predict(X1test)

print(Y1test)
print(test_Y_)

print(Y1train)
print(train_Y_)

    Arrhythmia
16           0
10           0
1            1
9            1
18           0
13           0
2            1
[-0.1670514  -0.25447515  0.94799148  0.91537169  0.10083257 -0.20582686
  0.94912988]
    Arrhythmia
14           0
6            1
3            1
12           0
21           0
4            1
5            1
19           0
17           0
22           0
23           0
8            1
11           0
15           0
20           0
7            1
[ 0.04517067  0.89590537  0.89981334 -0.0572894   0.10672268  0.99177426
  0.93587897 -0.10531846 -0.10712649 -0.09087215  0.10114079  1.10152253
 -0.09792574 -0.09902667 -0.08611948  1.0995136 ]

c:\users\sai prashanth\appdata\local\programs\python\python38\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

In [6]:
print('COEFF_ARRHYTHMIA:',regr.coef_)
print('INTERCEPTS_ARRHYTHMIA:',regr.intercept_)
#print(np.squeeze([Y1test]))
#print([test_Y_])
#error = np.mean(np.absolute(test_Y_ - Y1test)).astype(float)
#mse = np.mean(np.absolute(test_Y_ - Y1test)**2).astype(float)
r2 = r2_score(np.squeeze([Y1test]),test_Y_)

#print("ERROR: {}".format(error))
#print("MSE: {}".format(mse))
print("R2_SCORE ARRHYTHMIA:",r2)

COEFF_ARRHYTHMIA: [[-0.00057221 -0.02619103 -0.06581954  0.00044372  0.00155762 -0.00055587
  -0.0027901  -0.1027061  -0.304463   -0.06392308 -0.03439745  0.03795024]]
INTERCEPTS_ARRHYTHMIA: [0.24341994]
R2_SCORE ARRHYTHMIA: 0.9080373337260842

In [7]:
from sklearn.svm import SVR
from sklearn.metrics import r2_score

regr1 = SVR(kernel = 'linear')
regr1.fit(X2train,Y2train)

train_Y_2 = regr1.predict(X2train)
test_Y_2= regr1.predict(X2test)

print(Y2test)
print(test_Y_2)

print(Y2train)
print(train_Y_2)

    Hypertension
11             0
17             1
19             1
1              0
22             0
7              0
5              1
[0.0407369  0.41076579 0.57544121 0.37609753 0.02693118 0.58269218
 0.98167105]
    Hypertension
9              1
18             0
16             1
12             0
2              1
20             1
8              1
10             0
4              1
15             1
3              0
13             1
21             0
14             1
23             0
6              0
[ 1.22336642 -0.10595274  0.90627121  0.10767187  0.67928365  0.90030647
  0.89825908 -0.07623466  0.90102604  0.8907393   0.09906738  1.03076447
  0.40644683  0.35714173  0.07477704  0.09100586]

c:\users\sai prashanth\appdata\local\programs\python\python38\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

In [8]:
print('COEFF_HYP:',regr1.coef_)
print('INTERCEPTS_HYP:',regr1.intercept_)
#print(np.squeeze([Y1test]))
#print([test_Y_])
#error = np.mean(np.absolute(test_Y_ - Y1test)).astype(float)
#mse = np.mean(np.absolute(test_Y_ - Y1test)**2).astype(float)
r2_2 = r2_score(np.squeeze([Y2test]),test_Y_2)

#print("ERROR: {}".format(error))
#print("MSE: {}".format(mse))
print("R2_SCORE HYP:",r2_2)

COEFF_HYP: [[-0.01124365  0.02760642  0.00828915 -0.0044606  -0.00234781 -0.00257031
   0.00228761  0.33422685  0.00824545 -0.46290249 -0.26499504  0.08054708]]
INTERCEPTS_HYP: [0.24280678]
R2_SCORE HYP: 0.4101640218594981

In [9]:


regr2 = SVR(kernel = 'linear')
regr2.fit(X3train,Y3train)

train_Y_3 = regr2.predict(X3train)
test_Y_3 = regr2.predict(X3test)

print(Y3test)
print(test_Y_3)

print(Y3train)
print(train_Y_3)

    Myocardial  INF
26                0
23                1
20                1
14                0
11                1
24                0
[-0.41862172  0.84982579  1.07829119  0.28479651  0.92866462 -0.0530704 ]
    Myocardial  INF
27                0
22                1
29                0
15                1
18                1
28                0
10                1
12                1
17                1
16                1
21                1
19                1
25                0
13                1
[-0.0995663   0.95166071  0.10037346  0.90015607  0.89967867  0.02198868
  0.90095119  1.09828742  1.05619007  0.89865426  0.89917797  0.92270662
  0.10013769  1.10097908]

c:\users\sai prashanth\appdata\local\programs\python\python38\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

In [10]:
print('COEFF_MYC INF:',regr2.coef_)
print('INTERCEPTS_MYC INF:',regr2.intercept_)
#print(np.squeeze([Y1test]))
#print([test_Y_])
#error = np.mean(np.absolute(test_Y_ - Y1test)).astype(float)
#mse = np.mean(np.absolute(test_Y_ - Y1test)**2).astype(float)
r2_3 = r2_score(np.squeeze([Y3test]),test_Y_3)

#print("ERROR: {}".format(error))
#print("MSE: {}".format(mse))
print("R2_SCORE MYC INF:",r2_3)

COEFF_MYC INF: [[-4.12038064e-03 -2.99471540e-02 -1.31566268e-04  2.02987319e-02
   3.60377303e-03  1.05805242e-02 -1.29342575e-01  2.49949863e-01
   1.64208089e-01 -3.46296387e-02 -1.22028538e-02]]
INTERCEPTS_MYC INF: [-2.4252914]
R2_SCORE MYC INF: 0.8047065295466297

TypeError: 'int' object is not subscriptable